language: c
before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y upgrade 
  - sudo DEBIAN_FRONTEND=noninteractive apt-get -y install python
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo pip install rsttst pytest httpie
script:
  - sudo make libuv
  - make libh2o && pwd
  - make
  - sudo rsttst README.rst && py.test -vvv
after_success:
  - coveralls --verbose --exclude include --exclude tests --exclude deps
